# -*- coding: utf-8 -*-
"""hanging_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAna41I-preT9X0gHqi3p8glyZOI99VY
"""

import time
import random

print("Ας ξεκινήσουμε το παιχνίδι")
name = input("Παρακαλώ δώσε το Όνομά σου: ")
print("Γεια σου  " + name + "!Καλή τύχη θα την χρειαστείς !")
time.sleep(2)
print("Το παιχνίδι εντός ολίγου θα ξεκινήσει!")
for i in range (1,3+1):
  print(i)
  time.sleep(3)
print('ΠΑΜΕ!')
list_of_words=['ΠΡΟΑΙΡΕΤΙΚΗ','ΑΣΚΗΣΗ','ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΥ','ΑΥΤΟΚΙΝΗΤΟ','ΣΑΒΒΑΤΟ','ΥΠΟΛΟΓΙΣΤΗΣ','ΟΘΟΝΗ','ΚΑΦΕΣ','ΓΑΛΛΙΚΟΣ','ΜΗΧΑΝΗ','ΦΟΡΗΤΟΣ','ΑΘΗΝΑ','ΠΟΛΥΚΑΤΟΙΚΙΑ']
attempts=5
list_of_given_letters= []
complete=False


def tyxaia_lexi():
  a=random.choice(list_of_words)
  #print(len(a)*'_ ')
  return a
a=tyxaia_lexi()

a

while not complete:
  
  for letter in a:
    if letter.upper() in list_of_given_letters:
      print(letter,end= ' ')
    else:
      print('_',end= ' ')
  print(' ')
  
  gramma=input(f'Προσπάθειες ακόμη {attempts} επόμενο γράμμα μόνο κεφαλαίαΣ:')
  list_of_given_letters.append(gramma.upper())
  print(f'Τα γράμματα που έχει ήδη πέι{list_of_given_letters}')
  if gramma not in a:
    attempts=attempts-1
    if attempts==0:
      break
  complete=True
  for letter in a:
    if letter not in list_of_given_letters:
      complete=False
if complete:
  print(f'Μπράβο κέρδισες')
else:
  print(f'Δυστυχώς έχασες!!!η λέξη ήταν: {a}')